---
- name: Remove all VMs in VMware datacenter
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_user }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
    register: vm_info

  - name: Power off all VMs
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_user }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      name: "{{ item.guest_name }}"
      state: powered-off
    loop: "{{ vm_info.virtual_machines }}"
    ignore_errors: yes

  - name: Remove all VMs
    community.vmware.vmware_guest:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_user }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      name: "{{ item.guest_name }}"
      state: absent
      force: yes
    loop: "{{ vm_info.virtual_machines }}"