vsphere_host: "vcsrs00-vc.infra.demo.redhat.com"
vsphere_user: "etx-dev@vsphere.local"
vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
datacenter: "RS00"
cluster: "vcs-rs-00"
datastore: "workload_share_QHFNI"
students_count: 50
folder_name_prefix: "student-"
parent_folder: ETX
vm_templates:
  - { name: "roadshow-tpl-winweb01", vm_name: "winweb", folder: "OCPVirtRoadShow", powerState: "poweredoff" }
  - { name: "etx-win2019-template", vm_name: "win2019", folder: "ETX_Templates", powerState: "poweredoff" }
  - { name: "rhel86-tpl", vm_name: "rhel86", folder: "RHEL", powerState: "poweredoff" }
  - { name: "rhel93-tpl", vm_name: "rhel93", folder: "RHEL", powerState: "poweredoff" }  