---
# Migration Factory Base Inventory

# This inventory file contains common variable for the Migration Factory that
# should not require modifications. Variables that should be modified to suit the environment
# should be made in a separate inventory file

all:
  # Variables that are applied to all Inventory Groups
  vars:

    # OpenShift Configurations
    aap_namespace: migration-factory
    aap_version: 2.5
    aap_channel: stable-2.5
    aap_instance_name: aap-etx

    # AAP Configurations
    aap_project: Migration
    aap_org_name: MTV
    controller_validate_certs: false

    # Git Repository Details
    aap_project_repo: https://gitlab.consulting.redhat.com/redhat-cop/vmware-openshift-virt-migration/virt_migration_factory.git
    aap_project_branch: main

    # Execution Environment Details
    container_host: quay.io/redhat-cop
    aap_execution_environment: Migration Factory
    aap_execution_environment_image: quay.io/redhat-cop/virt-migration-factory-ee:2.5-v1.0.0

    # Automation Hub Configurations. These are not utilized within the workshop, but still needs to be defined
    automation_hub_certified_url: https://cloud.redhat.com/api/automation-hub/content/published/
    automation_hub_certified_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    automation_hub_certified_token: notused
    
    automation_hub_validated_url: https://cloud.redhat.com/api/automation-hub/content/validated/
    automation_hub_validated_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    automation_hub_validated_token: notused

    # OpenShift Operators that are installed via the Migration Factory deployment
    aap_seed_operator_management_hub: []
    aap_seed_operator_management_spoke:
      - nmstate
    
    # MTV Configurations
    mtv_vmware_vddk_init_image: quay.io/redhat-cop/virt-migration-factory-vddk:latest

# Migration Factory Hub clusters to configure
migration_factory_hub:
  hosts:
    etx.redhat.com:
      openshift_verify_ssl: false

      # Install AAP on the Hub cluster
      install_aap: true

# Migration Factory Spoke clusters to configure
migration_factory_spoke:
  hosts:
    etx.redhat.com:
      openshift_verify_ssl: false
...
